import { jsPDF } from 'jspdf';

// ─── Score color logic (mirrors ResumeAnalyzer's scoreColor) ────────
function getScoreColor(score) {
  if (score >= 8) return { r: 34, g: 197, b: 94, label: 'Excellent' };   // green
  if (score >= 6) return { r: 10, g: 102, b: 194, label: 'Good' };      // brand blue
  if (score >= 4) return { r: 245, g: 158, b: 11, label: 'Needs Work' }; // amber
  return { r: 239, g: 68, b: 68, label: 'Poor' };                        // red
}

// ─── Format a Date to a readable string ─────────────────────────────
function formatDate(date) {
  return new Date(date).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

// ─── Footer on every page ───────────────────────────────────────────
function addFooter(doc) {
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    // Thin line above footer
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.3);
    doc.line(20, pageHeight - 18, pageWidth - 20, pageHeight - 18);

    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by InternIQ — interniq.vercel.app', 20, pageHeight - 12);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 20, pageHeight - 12, { align: 'right' });
  }
}

// ─── Check if we need a new page ────────────────────────────────────
function ensureSpace(doc, y, needed, margin = 25) {
  const pageHeight = doc.internal.pageSize.getHeight();
  if (y + needed > pageHeight - margin) {
    doc.addPage();
    return 35; // reset y after top margin on new page
  }
  return y;
}

// ─── Main export function ───────────────────────────────────────────
export function generateReportPDF({ fileName, atsScore, scoreReasoning, improvements, analyzedAt }) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - 40; // 20mm margins each side
  let y = 20;

  // ━━━━━━━━━━ HEADER ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(10, 102, 194); // #0A66C2
  doc.text('InternIQ', 20, y);

  y += 9;
  doc.setFontSize(13);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text('Resume Analysis Report', 20, y);

  y += 5;
  doc.setDrawColor(10, 102, 194);
  doc.setLineWidth(0.6);
  doc.line(20, y, pageWidth - 20, y);
  y += 10;

  // ━━━━━━━━━━ SUMMARY SECTION ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // File name
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(120, 120, 120);
  doc.text('FILE ANALYZED', 20, y);
  y += 5;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(50, 50, 50);
  doc.text(fileName || 'Unknown file', 20, y);

  y += 8;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(120, 120, 120);
  doc.text('DATE OF ANALYSIS', 20, y);
  y += 5;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(50, 50, 50);
  doc.text(formatDate(analyzedAt || new Date()), 20, y);
  y += 14;

  // ── ATS Score ─────────────────────────────────────────────────────
  const { r, g, b, label } = getScoreColor(atsScore);

  // Score background box
  doc.setFillColor(r, g, b);
  doc.roundedRect(20, y, 50, 28, 4, 4, 'F');

  // Score text inside box
  doc.setFontSize(32);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text(`${atsScore}/10`, 45, y + 18, { align: 'center' });

  // Label beside the box
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(r, g, b);
  doc.text(label, 78, y + 10);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text('ATS Compatibility Score', 78, y + 18);

  y += 36;

  // ── Score reasoning ───────────────────────────────────────────────
  if (scoreReasoning) {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(120, 120, 120);
    doc.text('SCORE REASONING', 20, y);
    y += 5;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(60, 60, 60);
    const reasoningLines = doc.splitTextToSize(scoreReasoning, contentWidth);
    for (const line of reasoningLines) {
      y = ensureSpace(doc, y, 6);
      doc.text(line, 20, y);
      y += 5;
    }
  }

  y += 8;

  // ━━━━━━━━━━ IMPROVEMENT AREAS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  if (improvements && improvements.length > 0) {
    y = ensureSpace(doc, y, 20);

    // Section divider
    doc.setDrawColor(220, 220, 220);
    doc.setLineWidth(0.3);
    doc.line(20, y, pageWidth - 20, y);
    y += 8;

    doc.setFontSize(15);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(10, 102, 194);
    doc.text('Areas for Improvement', 20, y);

    y += 3;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(150, 150, 150);
    doc.text(`${improvements.length} item${improvements.length !== 1 ? 's' : ''} identified`, 20, y);
    y += 10;

    improvements.forEach((item, idx) => {
      // Estimate space needed for this item (area title + issue + suggestion)
      const issueLines = doc.splitTextToSize(item.issue || '', contentWidth - 10);
      const suggestionLines = doc.splitTextToSize(item.suggestion || '', contentWidth - 10);
      const estimatedHeight = 12 + (issueLines.length * 5) + 8 + (suggestionLines.length * 5) + 10;

      y = ensureSpace(doc, y, Math.min(estimatedHeight, 60));

      // Area number + name
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(40, 40, 40);
      doc.text(`${idx + 1}. ${item.area}`, 20, y);
      y += 7;

      // Issue
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(239, 68, 68); // red
      doc.text('Issue:', 24, y);
      y += 5;

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(70, 70, 70);
      for (const line of issueLines) {
        y = ensureSpace(doc, y, 6);
        doc.text(line, 24, y);
        y += 5;
      }

      y += 3;

      // Suggestion
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(5, 122, 85); // dark green
      doc.text('Suggestion:', 24, y);
      y += 5;

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(5, 122, 85);
      for (const line of suggestionLines) {
        y = ensureSpace(doc, y, 6);
        doc.text(line, 24, y);
        y += 5;
      }

      y += 8;

      // Subtle divider between items (except after the last one)
      if (idx < improvements.length - 1) {
        y = ensureSpace(doc, y, 4);
        doc.setDrawColor(230, 230, 230);
        doc.setLineWidth(0.2);
        doc.line(24, y, pageWidth - 24, y);
        y += 6;
      }
    });
  }

  // ━━━━━━━━━━ FOOTER (all pages) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  addFooter(doc);

  // ━━━━━━━━━━ SAVE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  const cleanName = (fileName || 'resume').replace(/\.[^/.]+$/, '');
  doc.save(`InternIQ_Resume_Report_${cleanName}.pdf`);
}
